export const ADD_ENTREE='ADD_ENTREE';
export const SHOW_ENTREES='SHOW_ENTREES';
export const SHOW_ENTREE='SHOW_ENTREE';
export const EDIT_ENTREE='EDIT_ENTREE';
export const DELETE_ENTREE='DELETE_ENTREE';