export const GET_INGREDIENTS_BY_DISH_ID='GET_INGREDIENTS_BY_DISH_ID';
export const ADD_INGREDIENT_TO_DISH='ADD_INGREDIENT_TO_DISH';
export const DELETE_INGREDIENT_TO_DISH='DELETE_INGREDIENT_TO_DISH';
export const UPDATE_INGREDIENT_TO_DISH='UPDATE_INGREDIENT_TO_DISH';
export const CLEAR_INGREDIENTS_BY_DISH='CLEAR_INGREDIENTS_BY_DISH';