export const ADD_INGREDIENT='ADD_INGREDIENT';
export const SHOW_INGREDIENTS='SHOW_INGREDIENTS';
export const SHOW_INGREDIENT='SHOW_INGREDIENT';
export const EDIT_INGREDIENT='EDIT_INGREDIENT';
export const DELETE_INGREDIENT='DELETE_INGREDIENT';
export const GET_INGREDIENTS_BY_DISH_ID='GET_INGREDIENTS_BY_DISH_ID';
export const ADD_INGREDIENT_TO_DISH='ADD_INGREDIENT_TO_DISH';
export const DELETE_INGREDIENT_TO_DISH='DELETE_INGREDIENT_TO_DISH';