export const ADD_INGREDIENT='ADD_INGREDIENT';
export const SHOW_INGREDIENTS='SHOW_INGREDIENTS';
export const SHOW_INGREDIENT='SHOW_INGREDIENT';
export const EDIT_INGREDIENT='EDIT_INGREDIENT';
export const DELETE_INGREDIENT='DELETE_INGREDIENT';