export const GET_INVOICES='GET_INVOICES';
export const DELETE_INVOICE='DELETE_INVOICE';
export const SHOW_INVOICE='SHOW_INVOICE';
export const EDIT_INVOICE='EDIT_INVOICE';
export const SHOW_ORDER_PRODUCTS='SHOW_ORDER_PRODUCTS';