export const ADD_STRONG_DISH='ADD_STRONG_DISH';
export const SHOW_STRONGS_DISHES='SHOW_STRONGS_DISHES';
export const SHOW_STRONG_DISH='SHOW_STRONG_DISH';
export const EDIT_STRONG_DISH='EDIT_STRONG_DISH';
export const DELETE_STRONG_DISH='DELETE_STRONG_DISH';